import { Platform, StyleSheet } from 'react-native';
import { theme } from '../../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.backgroundBase,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: Platform.OS === 'android' ? 40 : 16,
  },
  headerIcon: {
    padding: 4,
  },
  headerAvatarContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.colors.outlineVariantAlpha,
  },
  headerAvatar: {
    width: '100%',
    height: '100%',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 110,
  },
  profileSection: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 40,
  },
  avatarWrapper: {
    position: 'relative',
    width: 140,
    height: 140,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarGlow: {
    position: 'absolute',
    width: 156,
    height: 156,
    borderRadius: 78,
    opacity: 0.5,
  },
  mainAvatar: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 2,
    borderColor: theme.colors.backgroundBase,
  },
  editButton: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.primaryAccent,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.colors.backgroundBase,
  },
  userName: {
    ...theme.typography.displayMedium,
    color: theme.colors.textPrimary,
    marginBottom: 8,
    textTransform: 'capitalize',
  },
  userSubtitle: {
    ...theme.typography.metadata,
    color: theme.colors.textSecondary,
    letterSpacing: 1.5,
  },
  sectionContainer: {
    marginBottom: 32,
  },
  sectionHeader: {
    ...theme.typography.metadata,
    color: theme.colors.textSecondary,
    letterSpacing: 2,
    marginBottom: 16,
    marginLeft: 4,
  },
  cardContainer: {
    padding: 0,
    borderRadius: theme.radius.xl,
    backgroundColor: theme.colors.backgroundCard,
    overflow: 'hidden',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.backgroundInteractive,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  itemTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  itemTitle: {
    ...theme.typography.body,
    color: theme.colors.textPrimary,
    fontWeight: '600',
    marginBottom: 2,
  },
  itemSubtitle: {
    ...theme.typography.metadata,
    color: theme.colors.textMuted,
  },
  itemTitleLink: {
    ...theme.typography.body,
    color: theme.colors.textPrimary,
    fontWeight: '600',
    flex: 1,
  },
  chevron: {
    color: theme.colors.textMuted,
    fontSize: 24,
    fontWeight: '300',
    paddingHorizontal: 8,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.outlineVariantAlpha,
    marginLeft: 72,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: theme.radius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 110, 132, 0.3)',
    backgroundColor: 'rgba(255, 110, 132, 0.05)',
    marginTop: 16,
    marginBottom: 32,
  },
  logoutText: {
    ...theme.typography.body,
    color: theme.colors.error,
    fontWeight: '600',
    marginLeft: 12,
  },
  versionText: {
    ...theme.typography.metadata,
    color: theme.colors.textMuted,
    textAlign: 'center',
    letterSpacing: 1.5,
  },
});
