import { StyleSheet } from 'react-native';
import { theme } from '../../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.backgroundBase,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 110,
    alignItems: 'center',
  },
  headerSection: {
    marginBottom: 48,
    alignItems: 'center',
  },
  profileTitle: {
    ...theme.typography.displayMedium,
    color: theme.colors.textPrimary,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  avatarContainer: {
    width: 156,
    height: 156,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
    position: 'relative',
  },
  avatarGlow: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    opacity: 0.15,
  },
  avatarCircle: {
    width: 156,
    height: 156,
    borderRadius: 78,
    backgroundColor: theme.colors.backgroundCard,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: theme.colors.secondaryAccent,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 8,
  },
  infoSection: {
    alignItems: 'center',
    marginBottom: 64,
  },
  userName: {
    ...theme.typography.displayMedium,
    color: theme.colors.textPrimary,
    fontWeight: '700',
    marginBottom: 4,
    textAlign: 'center',
  },
  userEmail: {
    ...theme.typography.body,
    color: theme.colors.textSecondary,
    opacity: 0.7,
    fontWeight: '500',
  },
  actionsContainer: {
    width: '100%',
    gap: 16,
  },
  premiumBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(147, 51, 234, 0.1)',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(147, 51, 234, 0.2)',
    marginBottom: 40,
  },
  premiumText: {
    ...theme.typography.metadata,
    color: theme.colors.secondaryAccent,
    fontWeight: '700',
    letterSpacing: 1,
    marginLeft: 8,
  },
  logoutButton: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    borderRadius: 20,
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  logoutText: {
    ...theme.typography.body,
    color: '#ef4444',
    fontWeight: '700',
    marginLeft: 12,
  },
  versionText: {
    marginTop: 48,
    ...theme.typography.metadata,
    color: theme.colors.textMuted,
    opacity: 0.5,
    letterSpacing: 2,
  },
});
