import { StyleSheet } from "react-native";
import { theme } from "../../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.backgroundBase,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
    gap: 16,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: theme.colors.backgroundCard,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  headerTitle: {
    ...theme.typography.headline,
    color: theme.colors.textPrimary,
    fontSize: 22,
  },
  headerSubtitle: {
    ...theme.typography.body,
    color: theme.colors.textSecondary,
    fontSize: 14,
    opacity: 0.7,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
    flexGrow: 1,
  },
  listHeader: {
    gap: 18,
    paddingBottom: 18,
  },
  tabsWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 18,
    padding: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  tabButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  tabButtonActive: {
    backgroundColor: theme.colors.backgroundCard,
  },
  tabButtonDisabled: {
    opacity: 0.45,
  },
  tabLabel: {
    ...theme.typography.label,
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  tabLabelActive: {
    color: theme.colors.textPrimary,
  },
  tabLabelDisabled: {
    color: theme.colors.textMuted,
  },
  tabCountPill: {
    minWidth: 24,
    height: 24,
    borderRadius: 999,
    paddingHorizontal: 7,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  tabCountPillActive: {
    backgroundColor: theme.colors.primaryAccent,
  },
  tabCountPillDisabled: {
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  tabCountText: {
    ...theme.typography.label,
    color: theme.colors.textMuted,
    fontSize: 10,
    fontWeight: "700",
  },
  tabCountTextActive: {
    color: theme.colors.backgroundBase,
  },
  tabCountTextDisabled: {
    color: theme.colors.textMuted,
  },
  sectionHero: {
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionHeroText: {
    flex: 1,
    gap: 6,
  },
  sectionTitle: {
    ...theme.typography.label,
    color: theme.colors.textPrimary,
    fontSize: 14,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  sectionCaption: {
    ...theme.typography.body,
    color: theme.colors.textSecondary,
    fontSize: 13,
    opacity: 0.8,
  },
  badge: {
    backgroundColor: theme.colors.primaryAccent,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    minWidth: 34,
    minHeight: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    ...theme.typography.label,
    color: theme.colors.backgroundBase,
    fontSize: 11,
    fontWeight: "bold",
  },
  listRow: {
    marginBottom: 12,
  },
  listRowCompleted: {
    marginBottom: 4,
  },
  processingCard: {
    width: "100%",
    gap: theme.spacing.sm,
    alignItems: "flex-start",
    justifyContent: "space-between",
    borderRadius: 18,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    backgroundColor: "rgba(255,255,255,0.025)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.045)",
  },
  processingCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  artworkWrap: {
    width: theme.spacing.xxl,
    height: theme.spacing.xxl,
    borderRadius: theme.radius.sm,
    overflow: "hidden",
    backgroundColor: theme.colors.backgroundInteractive,
    marginRight: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  artwork: {
    width: "100%",
    height: "100%",
  },
  processingTextWrap: {
    flex: 1,
    gap: 6,
  },
  processingTopRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  jobTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.spacing.md - 1,
    fontWeight: "bold",
    flexShrink: 1,
  },
  jobSubtitle: {
    color: theme.colors.textSecondary,
    fontSize: theme.spacing.sm + theme.spacing.xs,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  statusLabel: {
    ...theme.typography.label,
    color: theme.colors.textMuted,
    fontSize: 11,
    fontWeight: "600",
  },
  statusLabelActive: {
    color: theme.colors.primaryAccent,
  },
  statusLabelFailed: {
    color: theme.colors.error,
  },
  progressText: {
    marginLeft: "auto",
    ...theme.typography.label,
    color: theme.colors.secondaryAccent,
    fontSize: 10,
    fontWeight: "700",
  },
  progressBarTrack: {
    height: 4,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: theme.colors.primaryAccent,
    borderRadius: 999,
  },
  errorText: {
    color: theme.colors.error,
    fontSize: 11,
    lineHeight: 16,
  },
  processingCardBottom: {
    width: "100%",
    gap: theme.spacing.xs,
  },
  processingCardAction: {
    width: 36,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: theme.spacing.sm,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 72,
    gap: 16,
  },
  emptyTitle: {
    ...theme.typography.headline,
    color: theme.colors.textPrimary,
    fontSize: 18,
  },
  emptySubtitle: {
    ...theme.typography.body,
    color: theme.colors.textSecondary,
    textAlign: "center",
    paddingHorizontal: 40,
    fontSize: 14,
    lineHeight: 20,
    opacity: 0.6,
  },
});
